### ISSUE TITLE
Is the Decrypter useable with Safari

### ISSUE THREAD

**Issue by Petschko** [Petschko/RPG-Maker-MV-Decrypter#11]
If someone has a Safari Browser, please tell me if it works. It would be super kind of you

_(If not, please be detailed what doesn't work etc)_

**Comment by fz0000** [comment]
Test both online and offline.
"Save" is OK.
Error occurs when click "View". See screenshot for details
Hardware: Mac mini
OS: MacOS Sierra 10.12.6
Safari version: 12.1

![image](https://user-images.githubusercontent.com/5061311/58447376-b9fb9300-8136-11e9-9c95-61bb13d95f8b.png)

**Comment by Petschko** [comment]
Could be the same issue like with IE/Edge, so just "View" doesn't work here as well. Thank you!

**Comment by Continuous-exile** [comment]
Safari16.1(macOS13.2.1)一切正常，感谢您分享这份好用的工具

**Comment by fz0000** [comment]
Verified on latest code (online and offline v2.2.0).
"View" works well now. See screenshot for details.
Thanks.

OS ver: macOS Ventura 13.3
Safari ver: 16.4

<img width="509" alt="image" src="https://user-images.githubusercontent.com/5061311/230177229-bd95ce1c-eebb-47c6-b3d1-615532158629.png">

**Comment by Petschko** [comment]
Yay thats epic, thanks for letting me know!
