### ISSUE TITLE
Is the Decrypter useable with Opera

### ISSUE THREAD

**Issue by Petschko** [Petschko/RPG-Maker-MV-Decrypter#12]
If someone has the Opera Browser, please tell me if it works. It would be super kind of you

_(If not, please be detailed what doesn't work etc)_

**Comment by SandR0ck2003** [comment]
Tested with current Opera. Everything works but download zip button. Caused it to error saying out of memory with a few files or the whole img dir of a game.

**Comment by Petschko** [comment]
Thanks for testing! Yeah I still have problems with the ZIP-Download... But thanks to you I know it also doesn't work in Opera...

See: https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues/14
