### ISSUE TITLE
ZIP Download doesn't work anymore (Some Browsers)

### ISSUE THREAD

**Issue by Petschko** [Petschko/RPG-Maker-MV-Decrypter#14]
I tried to decrypt a bunch of Files for someone  but I saw that my Firefox (on Fedora 26) freezes if I try to Download the Files as ZIP... So I have to investigate why

**Comment by Petschko** [comment]
I use now [FileSaver.js](https://github.com/eligrey/FileSaver.js) to Download the ZIP-File. I tested it with 150 Files and my Browser (Firefox) just downloaded it perfect after that change! - See: https://github.com/Petschko/RPG-Maker-MV-Decrypter/commit/a58367a709e67e59645fe72019bc9479114512a7
Can please someone test Opera?

**Comment by fz0000** [comment]
Test with 700+ files with Opera 60.0.3255.109 and it works well.

**Comment by Petschko** [comment]
Thank you!^^
