### ISSUE TITLE
Doesn't work anymore on new Rpgm versions

### ISSUE THREAD

**Issue by Mai1124** [Petschko/RPG-Maker-MV-Decrypter#17]
hey man could you please update your tool ? It doesn't detect Decryption-Code anymore.

**Comment by Petschko** [comment]
Are you sure that this is with all new Versions? Sometimes people try to hide the  Code somewhere else. If you want you can send me the Project and I check it out myself. ( Please upload it on a Private spot and send me the Link via Mail to peter@petschko.org )

**Comment by Mai1124** [comment]
sent it.Thanks again

**Comment by Petschko** [comment]
Its a Game, where the Author moved the Decryption-Key to the File `rpg_core.js`

I get from time to time questions about this Game... Its not a new Version from RPGMV, it's just a trick to avoid Decryption Software like mine^^
