### ISSUE TITLE
Can not find out the Key from rpg_core.js

### ISSUE THREAD

**Issue by Aqqqq1234** [Petschko/RPG-Maker-MV-Decrypter#20]
As you explained here(https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues/19) how the get the key from rpg_core.js file. I opened rpg_core.js file in the workpad, use the search option (Ctrl+F) and search for "Decrypter.readEncryptionkey" in the file however, I get the result as this:

Decrypter.readEncryptionkey = function(){
    this._encryptionKey = $dataSystem.encryptionKey.split(/(.{2})/).filter(Boolean);

So I could not get the key. And as you can understand I am not good with coding etc. 

Note that I tried the system.json detection tool first. 

Thank you in advance

**Comment by Petschko** [comment]
Hey,
please send the rpg_core.js file, it seems, that the key is NOT in this file, but it should show a message instead of snipets of JS code...

**Comment by Petschko** [comment]
Is this issue still open, if yes please send the rpg_core.js file, so that I can figure out whats happening there

**Comment by Petschko** [comment]
People can detect the code their self by adding this code https://github.com/Petschko/RPG-Maker-MV-Decrypter/blob/master/readKeyFromGame.js
to the very end of the `rpg_core.js`

Lately more and more games try to obfuscate the Encryption-Code, this is a way how we hack ourselfs into the game and can retrieve the key at the decryption method, so no matter how much its obfuscated, the code will be shown
