### ISSUE TITLE
Error: File-Content was invalid (Was not a JSON-File)

### ISSUE THREAD

**Issue by subdance** [Petschko/RPG-Maker-MV-Decrypter#21]
I selected the System.json file, after click detect button , this showed up:
'Error: File-Content was invalid (Was not a JSON-File)'
Why? I ' m pretty sure that i choose the right .json(www/data/system.json)

**Comment by Petschko** [comment]
Hey! Please upload the system.json somewhere (pastbin or here) and show me how it looks
