### ISSUE TITLE
Decryption-Code doesn't convert to viewable content

### ISSUE THREAD

**Issue by Qunarti** [Petschko/RPG-Maker-MV-Decrypter#23]
Hello,

I tried to decrypt this file using the system.json code - 90b329161632b112351d264196c31dad
However, the image cannot be viewed. Here are the .json, .js and the .rpgmvp

Any ideas that might work?

Thanks.
[Ada_Fairy_Dress.zip](https://github.com/Petschko/RPG-Maker-MV-Decrypter/files/3026220/Ada_Fairy_Dress.zip)

**Comment by Petschko** [comment]
Did you tried to decrypt any other file?

**Comment by Petschko** [comment]
I close this due inactivity and no response
