### ISSUE TITLE
PNG file decoding errors

### ISSUE THREAD

**Issue by reinhard2** [Petschko/RPG-Maker-MV-Decrypter#24]
decrypter creates non-working PNG files that cannot be opened
![Balloon](https://user-images.githubusercontent.com/49465489/55848115-5527b180-5b65-11e9-83a7-1ff5e91f3f17.png)
[Balloon.zip](https://github.com/Petschko/RPG-Maker-MV-Decrypter/files/3061781/Balloon.zip)

**Comment by Petschko** [comment]
It seems a running gag here to open Issues without providing all information. (See last issues: https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues?q=is%3Aissue+is%3Aclosed )

- I need the Decryption Code or `System.json` File
- Please provide multiple Files as well
- Please provide the Name of the Game

**Comment by reinhard2** [comment]
[system.zip](https://github.com/Petschko/RPG-Maker-MV-Decrypter/files/3062951/system.zip)
[Systemjson.zip](https://github.com/Petschko/RPG-Maker-MV-Decrypter/files/3062956/Systemjson.zip)
fed1232cc399d2f7abc1d13940f271ab
Yorna: Monster Girl's Secret by Yeehaw Games 0.7а

**Comment by Petschko** [comment]
It seems it uses an other Layer of encryption as well, there is also additional code in the rpg_core.js which is usually non-existent
But didn't find out currently. Thanks for the link, without the whole game I could not help you else

**Comment by reinhard2** [comment]
thanks waiting for the decision of problems.

**Comment by Petschko** [comment]
When I build this project I was not to good with all the File-Header stuff etc, but I played a bit with my HEX-Editor and found out you can just use a standard PNG-Header (on images) to receive the images. No need for any Decryption-Key whatsoever .

The decryption key just has the use to re-encrypt it now, I will implement this into that project, which will allow much easier "decryption" and less failures (should be none at all)

**Comment by reinhard2** [comment]
I would like to know when there will be a test version. 
программа как я понимаю декодирует файлы дважды, и уже не заменить PNG-Header через  HEX-Editor. так как уже не является PNG encoding and it does not see other programs. (for game)

**Comment by Petschko** [comment]
I'm a bit confused what do you want to tell me with your last comment?

I can quickly give you a small form which includes the same as my suggestion to solve. I will post the link inside here~

**Comment by reinhard2** [comment]
I mean, just changing the PNG header doesn't work.
and the link(program) to address the issue can leave.

**Comment by fz0000** [comment]
By the way, the "encryptionKey" in the System.json is "fc1b4dc02a3fe2d0ef4f111e74175c9q" in the latest version(v0.8a) of the game.
The last char 'q' looks strange... 🤔

**Comment by Petschko** [comment]
Usually the Key contains only HEX-Chars, so the "q" is probably not correct?

Maybe the TE gave me older Files, I will re-check this

**Comment by Petschko** [comment]
So took a big look at this project it seems they using a Plugin named "Options bypass", which changes the encryption key via multiple functions:

```javascript
function b(string) { // Warn: Unused function
    var string = string; // Warn: Duplicate declaration
    string += "e2b2594f019";
    c(string);
};

function c(string) {
    var string = string;
    string += "43016a41d3";
    d(string);
};

function d(string) {
    var string = string.split(/(.{2})/);
    e(string);
};

function e(string) {
    string = string.filter(Boolean);
    f(string);
}

function f(string) {
    Decrypter._encryptionKey = string;
}
```

I could check this more, but since this is the first game with that I will not invest this further

My IDE tells me its unused, but when I debug the game these functions are called and set the encryption key to:
`f5e9ce22c51e2b2594f01943016a41d3`

Which works for decrypting!

Aka the key from the `System.json` is ignore by this game xP

**Comment by reinhard2** [comment]
спасибо. хорошая работа. 
function а(string) находится в фаиле YEP_BattleEngineCore

**Comment by reinhard2** [comment]
Thanks. good job. 
function a(string) is file YEP_BattleEngineCore

**Comment by Petschko** [comment]
I think its just placed randomly in files to avoid people finding them, especially how bad they are written, they look hacked in.

It does not matter since you can find out the string in no time, even if they use 100 different functions

**Comment by reinhard2** [comment]
Perhaps this is a temporary encryption while the game is demo. Since the other games from this author were not encrypted usually.

**Comment by Petschko** [comment]
Yeah that can may be, but it doesn't provide any protection like the normal encryption...

They could even go a step further and store them encrypted on a Web-Server and request them only if the game runs via xhr xD That would make it more complicated but even that would not provide protection. So I don't get the point

**Comment by reinhard2** [comment]
But at least it will postpone the hack time, if you use a regular descriptor. already 2 months have passed before the discovery of the encryption code.
