### ISSUE TITLE
Opening an image in browser

### ISSUE THREAD

**Issue by Dhdu** [Petschko/RPG-Maker-MV-Decrypter#26]
I'm unsure it's a bug or not but whenever I restore an image file and click view it will always open another tab full of moon runes. Downloading the img works fine but I don't want to download the imgs sometimes

![image](https://user-images.githubusercontent.com/40683332/95262676-69dc1880-07e1-11eb-9a1d-31ffe178d726.png)

**Comment by Petschko** [comment]
That bug should only appear in Chrome (and Chrome-Related browsers)

**Comment by Petschko** [comment]
See also: https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues/1

**Comment by Dhdu** [comment]
oh, sorry for the bother
