### ISSUE TITLE
.RPGMVO Won't show up

### ISSUE THREAD

**Issue by Xinstar285** [Petschko/RPG-Maker-MV-Decrypter#31]
When I try to convert the rpgmvo file, (Audio file) to .ogg, then it won't even let me, because when I open the file system, it says 'No items match your search.' I tried it with both of the 'choose your file' Buttons, and no, I didn't delete them. I checked afterwards. Help would be appreciated.

**Comment by Petschko** [comment]
Are you in the correct directory?
Also you can try to select "All-Files (*.*)"  for File-Types
<img width="1137" alt="Unbenannt" src="https://user-images.githubusercontent.com/673011/116119433-ba07c300-a6be-11eb-8348-a3b7aa4956f5.png">

**Comment by Petschko** [comment]
This seems solved... Feel free to reopen this issue, when you're back and still have that Problem

**Comment by Xinstar285** [comment]
Okay. Thanks!
