### ISSUE TITLE
 Yorna_1_3_5 game resource files can't be used.

### ISSUE THREAD

**Issue by Aelitr** [Petschko/RPG-Maker-MV-Decrypter#32]
When I unpack this game, it just outputs game resource files that can't be used, including audio and picture files. Everything can't be opened normally.
[erroefile.zip](https://github.com/Petschko/RPG-Maker-MV-Decrypter/files/6668959/erroefile.zip)

**Comment by Petschko** [comment]
Please provide more information, like how the file-structure looks like, what endings do the files have.

Can the files be decrypted? Did you tried the "No-Key" option? -> https://petschko.org/tools/mv_decrypter/#restore-images
