### ISSUE TITLE
Is Encryption Option disabled?

### ISSUE THREAD

**Issue by RedEyedRocker** [Petschko/RPG-Maker-MV-Decrypter#34]
![Screenshot.png](https://i.imgur.com/tyypeA6.png)

As you can see by the screenshot, the option to encrypt files is greyed out so is it disabled for some reason?

Because, on the website, there's no issue encrypting files.

**Comment by Petschko** [comment]
Yes the Encryption option isnt possible yet over the GUI, you can however encrypt via the Command-Line... Sadly Encryption could require multiple inputs and i didnt decided how to do it yet...

Beside this issue dont belongs to the Web-Project

**Comment by RedEyedRocker** [comment]
I tried it via command-line and it's giving me an error:
![Screenshot.png](https://i.imgur.com/ETNTpMT.png)

**Comment by Petschko** [comment]
Please send what commend you used

**Comment by RedEyedRocker** [comment]
> 
> 
> Please send what commend you used

Ah, I think you're replying via email so you didn't see the edit but It's working fine, I just had to run the batch file as administrator.

But here's the code:
```
@echo off
title RPG Maker MV;MZ Decrypter ^| Encryption Command-Line Tool by RedAISkye
cls
set currentDir=%~dp0
cd /d %currentDir%
echo.
echo.
echo Enter project path: (Leave blank ^for default "%currentDir%encrypt")
set /p projectPath=
echo.
echo.
if "%projectPath%"=="" (
    set projectPath=%currentDir%encrypt
    echo Enter encryption key: ^(Can't be left blank^)
) else (
    echo Enter encryption key: ^(Leave blank ^for default "auto"^)
)
set /p encryptionKey=
if "%encryptionKey%"=="" set encryptionKey=auto
echo.
echo.
java -jar "RPG Maker MV Decrypter.jar" encrypt "%projectPath%" "%currentDir%output" true %encryptionKey%
echo.
echo.
pause
```
