### ISSUE TITLE
how to decrypt multi files in batch, if any command line possible

### ISSUE THREAD

**Issue by lymslive** [Petschko/RPG-Maker-MV-Decrypter#37]
I found it is less efficiency to click and select only a single file each time, is there any way to decrpyt all files in some directory, and it would be better if support command line.

**Comment by Petschko** [comment]
Hello,

you CAN select multiple files at once.

**Comment by Petschko** [comment]
Side note: You can take a look at the Java-Version OR look at some other community projects, there are some only-command line tools for this
