### ISSUE TITLE
unable to decrypt files when there are none in the directory

### ISSUE THREAD

**Issue by h3oCharles** [Petschko/RPG-Maker-MV-Decrypter#39]
oh hi, i thought of decrypting a game, however the only game files that are visible are the .exe and the save file in www/save/persistent.rpgsave
is it still possible to extract game files from something like this?

I'm pretty sure it is an RPG Maker MV game, because the exe has this icon
![File0001](https://user-images.githubusercontent.com/8020330/211066684-1438ae8d-63a9-4b07-aa0a-0430a4ebcc5d.png)

**Comment by Petschko** [comment]
Its packed with an external program to make a single exe file. You have to "unpack" it first

**Comment by h3oCharles** [comment]
are there known tools for this

**Comment by Petschko** [comment]
I think it depends how this was packed, but i think most use this Enigma thing, there was some unpacker for that

**Comment by h3oCharles** [comment]
i sent an email regarding this
