### ISSUE TITLE
Suggestion:  webp support

### ISSUE THREAD

**Issue by Nazosan** [Petschko/RPG-Maker-MV-Decrypter#40]
I ran across a game with webp files.  In this case they were not encrypted, so there's no actual issue with that one, but it is possible or perhaps even likely that in the future there will be more games using webp instead of png.  The image decrypter seems to not want to work with webp files (in fact, it doesn't even list them in the open dialog) so this could be a potential problem in the future.  This is more a heads-up than anything else, but it does make sense that it should support webp anyway.

**Comment by Petschko** [comment]
Dont worry, when it comes to pictures, RPG Maker MV only encrypts PNGs, even JPGs are not encrypted by now.

**Comment by Nazosan** [comment]
That would explain why those weren't then.

If there is any possibility it might in the future perhaps they should be added as an option, but for now it certainly is a non-issue I can see.
