### ISSUE TITLE
not working for unknown reason :(

### ISSUE THREAD

**Issue by hachbr** [Petschko/RPG-Maker-MV-Decrypter#43]
i've used the site before, it worked great 
but this time it's just simply not working, and i'm doing everything the same as i did before 

i used it to extract sprites from the coffin of andy and leyley in the past, and it worked but it's not now :(  it seems someone else also had troubles extracting from this game recently

i'm on a macbook pro, and i tried using both chrome and firefox if that matters

**Comment by Petschko** [comment]
Duplicate https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues/42

**Comment by FailMuffin** [comment]
oh same bro
