### ISSUE TITLE
Issues with viewing decrypted image files

### ISSUE THREAD

**Issue by FailMuffin** [Petschko/RPG-Maker-MV-Decrypter#46]
I can't seem to view decrypted image files decrypted from rpgmvp for some reason

https://github.com/Petschko/RPG-Maker-MV-Decrypter/assets/139986757/a8a8318c-b860-4dfa-bf7b-715499486b30

**Comment by Petschko** [comment]
Does the File is actually decrypted? Try save it and view it on your computer, if it doesn't display on your computer that could be more reasons:

- They key you used was wrong
- The author of the game uses a custom encryption

If a file isn't decrypted properly, it can't be viewed in the browser either. Try to use the "Restore Images" tab before using the decryption method.

**Comment by FailMuffin** [comment]
ingore this I didn't see the restore image tab :P

**Comment by FailMuffin** [comment]
So, I tried doing that but it still doesn't work

![kill_1a (1)](https://github.com/Petschko/RPG-Maker-MV-Decrypter/assets/139986757/11ac1ca5-dcbe-419a-80d2-46d677022bfa)

Also I don't believe that the game uses a custom encryption

also if you need it here is the system, key, and game

[System.zip](https://github.com/Petschko/RPG-Maker-MV-Decrypter/files/12137180/System.zip)

d41d8cd98f00b204e9800998ecf8427e

The Coffin of Andy and Leyley Demo

**Comment by Petschko** [comment]
First:
- Please provide an example encrypted file of that game.
- Did you tried to use "Restore Images"?
- Did you tried to extract the Encryption-Key from an encrypted image?
     - If yes, is the Key from the image, the same as from the `system.json`?

**Comment by FailMuffin** [comment]
Please ignore me I am very stupid

**Comment by FailMuffin** [comment]
1 - [kill_1a.zip](https://github.com/Petschko/RPG-Maker-MV-Decrypter/files/12146490/kill_1a.zip)

2 - yes, I did

https://github.com/Petschko/RPG-Maker-MV-Decrypter/assets/139986757/38cf142e-a38b-4297-acb3-c3720df4c2b1



3 - Yes, the image key is different (and for some reason it still doesn't work
b9607e773d445f474c45493d79787462 - image

d41d8cd98f00b204e9800998ecf8427e - system

https://github.com/Petschko/RPG-Maker-MV-Decrypter/assets/139986757/95b902f4-89b0-4a97-8402-01f6cac64816

**Comment by Petschko** [comment]
Well that's an indicator they use something different. Technically the key from the image must be the same like from the system.json

**Comment by FailMuffin** [comment]
So, what's the problem here.

**Comment by FailMuffin** [comment]
And what the heck should I do

**Comment by Petschko** [comment]
Also see: https://github.com/Petschko/RPG-Maker-MV-Decrypter/issues/42
